config/routes.rb
Rails.application.routes.draw do
  
  root 'projects#index'
  
  devise_for :users

  resources :projects do
    resources :rewards, only: [:new, :create, :edit, :update, :destroy]
    resources :pledges
    resources :payments, only: [:new, :create]
  end
  
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  

end

app/models/reward.rb
# == Schema Information
#
# Table name: rewards
#
#  id                 :integer          not null, primary key
#  project_id         :integer
#  description        :text
#  value              :integer
#  shipping           :decimal(8, 2)
#  number_available   :integer
#  estimated_delivery :date
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

class Reward < ActiveRecord::Base

	belongs_to :project
	has_many   :pledges
	has_many   :backers, through: :pledges, source: :user

	validates :description, :value, :estimated_delivery, presence: true
	validates :value, numericality: { greater_than_or_equal_to: 0 }
	validates :number_available, numericality: { greater_than_or_equal_to: 0, allow_nil: true }
	validates :estimated_delivery, date: { after: Date.today }

end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
	before_action :authenticate_user!
	before_action :set_project
	before_action :set_reward, except: [:new, :create]
	load_and_authorize_resource :through => :project

	def new
		@reward = @project.rewards.build
		respond_to do |format|
			format.html
		end
	end

	def edit
	end

	def create
		@reward = @project.rewards.build(reward_params)
		respond_to do |format|
			if @reward.save
				format.html { redirect_to @project, notice: "Reward was successfully created!"}
			else
				format.html { render :new }
			end
		end
	end

	def update
		respond_to do |format|
		   if @reward.update(reward_params)
		   	format.html { redirect_to @project, notice: "Reward was successfully updated!" }
		   else
		   	format.html { render :edit }
		   end
		end
	end

	def destroy
		@reward.destroy
		respond_to do |format|
			format.html { redirect_to projects_path, notice: "Reward was successfully destroyed!"}
		end
	end

	private

	def set_project
		@project = Project.friendly.find(params[:project_id])
	end	

	def set_reward
		@reward = @project.rewards.find(params[:id])
	end

	def reward_params
		params.require(:reward).permit(:name, :description, :value, :shipping, :number_available, :estimated_delivery)
	end

end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/rewards/_form.html.erb
<%= simple_form_for([@project, @reward], html: { class: "form-horizontal" }) do |f| %>
	
	<%= f.input :description %>
	<%= f.input :value %>
	<%= f.input :shipping %>
	<%= f.input :number_available %>
	<%= f.input :estimated_delivery, :as => :date_picker %>
	
	<div class="actions">
		<%= f.button :submit %>	
	</div>
	
<% end %>

app/views/rewards/_reward.html.erb
<% if can? :manage, reward %>
	<div class="text-right">
		<%= link_to 'Edit',   edit_project_reward_path(@project, reward) %>
		<%= link_to 'Delete', project_reward_path(@project, reward), method: :delete, data: {confirm: "Are you sure?"} %>
	</div>
<% end %>

<%= link_to new_project_pledge_path(@project,reward_id:reward.id), class: "reward" do %>
	<div class="reward-box">
		<p class="pledge">Pledge $<%= reward.value %> or more</p>
		<p class="backers"><span class="primary-color"><i class="fa fa-cog"></i></span> <%= reward.backers.count %> backers</p>
		<p class="description"><%= reward.description %></p>
		<p class="time"><span class="grey">Estimated delivery:</span><br><%= reward.estimated_delivery %></p>
		<div class="reward-hover">
			Select this reward
		</div>
	</div>
<% end %>

app/views/rewards/edit.html.erb
<div class="container">
	<h1>Edit reward</h1>
	<%= render 'form' %>
</div>

app/views/rewards/new.html.erb
<div class="container">
	<h1>Add a new reward</h1>
	<%= render 'form' %>
</div>