config/routes.rb
Rails.application.routes.draw do
  
  root 'projects#index'
  
  devise_for :users

  resources :projects do
    resources :rewards, only: [:new, :create, :edit, :update, :destroy]
    resources :pledges
    resources :payments, only: [:new, :create]
  end
  
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
       <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "logo.svg", class: "logo" %>
       <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in?  %>
        <li><%= link_to "Start a Project", new_project_path %></li>
        <li><%= link_to "Account", edit_user_registration_path %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Log In", new_user_session_path %></li>
        <% end %>
      </ul>


    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stukstarter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Braintree JS -->
  <script type="text/javascript" src="https://js.braintreegateway.com/v2/braintree.js"></script>
  
</head>
<body>
<%= render "layouts/header" %>
<%= yield %>

</body>
</html>